### ISSUE TITLE
Non-Semver should be recognized if no "--separator" is provided

### ISSUE THREAD

**Issue by koppor** [marcaddeo/clparse#27]
Follow-up to https://github.com/marcaddeo/clparse/issues/22. Minor issue.

    clparse --format=json --separator=–

works great

   clparse --format=json

always outputs `null` as version.

I wonder whether it was possible that `version` is non-null, but `date` is null (because the separator is not known)

This might be too complex. Feel free to close the issue. My usecase works with `--separator=–`. Just wanted to share some ideas for "know-less" tooling :).

**Comment by marcaddeo** [comment]
Hi @koppor, this is happening because in order to parse the release information from the header I'm first splitting by the separator, i.e. ` – `. Then the left and right hand sides are parsed as the version and the date. 

Without knowing the correct separator at runtime, it does not attempt to parse the heading.

I'm not sure there's much reason to try and implement some sort of "separator guessing" here, or to potentially parse it differently.

**Comment by marcaddeo** [comment]
I guess it could just be a regular expression to match the separator, but again not sure if it's worth doing.
